package com.ty.supermarketappspringboot.dto;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.GenericGenerator;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonSetter;

import io.swagger.annotations.ApiModelProperty;
import lombok.AccessLevel;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Data
@Entity
public class Bill {
	@Id
	@GenericGenerator(name = "sequence_bill_id", strategy = "com.ty.supermarketappspringboot.dto.BillIdGenerator")
	@GeneratedValue(generator = "sequence_bill_id")
	@ApiModelProperty(value = "AutoGenerated")
	private String id;

	@NotNull(message = "Bill-LocalDate Is AutoGenerated")
	@ApiModelProperty(value = "AutoGenerated")
	private LocalDate localDate;

	@NotNull(message = "Bill-LocalTime Is AutoGenerated")
	@ApiModelProperty(value = "AutoGenerated")
	private LocalTime localTime;

	@NotNull(message = "Please Enter the Total-Product-Cost")
	@ApiModelProperty(value = "AutoGenerated")
	private double totalCost;

	@ManyToOne(cascade = CascadeType.PERSIST)
	@JoinColumn
	@JsonIgnore
	private Customer customer;

	@OneToMany(mappedBy = "bill", cascade = { CascadeType.MERGE, CascadeType.REMOVE, CascadeType.PERSIST })
	@JsonIgnore
	private List<BillProduct> billProducts;

	@Getter(value = AccessLevel.NONE)
	@Setter(value = AccessLevel.NONE)
	@Transient
	private List<Product> products;

	@JsonIgnore
	public List<Product> getProducts() {
		return products;
	}

	@JsonSetter
	public void setProducts(List<Product> products) {
		this.products = products;
	}

}
