package com.ty.supermarketappspringboot.dto;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.GenericGenerator;

import com.fasterxml.jackson.annotation.JsonIgnore;

import io.swagger.annotations.ApiModelProperty;
import lombok.AccessLevel;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Entity
@Data
public class Product {
	@Id
	@GenericGenerator(name = "sequence_product_id", strategy = "com.ty.supermarketappspringboot.dto.ProductIdGenerator")
	@GeneratedValue(generator = "sequence_product_id")
	@ApiModelProperty(value = "AutoGenerated")
	private String id;

	@NotBlank(message = "Please Enter The Product-Name")
	@ApiModelProperty(required = true)
	private String name;

	@NotBlank(message = "Please Enter The Product-Type")
	@ApiModelProperty(required = true)
	private String typeOfProduct;

	@NotBlank(message = "Please Enter The Product-Brand")
	@ApiModelProperty(required = true)
	private String brand;

	@NotNull(message = "Please Enter The Price-Of-Product")
	@ApiModelProperty(required = true)
	private double priceOfProduct;

	@NotNull(message = "Please Enter The Product-Quantity")
	@ApiModelProperty(required = true)
	private double quantityOfProduct;

	@OneToOne(cascade = CascadeType.ALL)
	@Getter(value = AccessLevel.NONE)
	@Setter(value = AccessLevel.NONE)
	@JoinColumn
	private ProductImage productImage;

	@JsonIgnore
	public ProductImage getProductImage() {
		return productImage;
	}

	@JsonIgnore
	public void setProductImage(ProductImage productImage) {
		this.productImage = productImage;
	}

	@ManyToOne
	@JoinColumn
	@JsonIgnore
	private Stock stock;

}
