package com.ty.supermarketappspringboot.dto;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;

import org.hibernate.annotations.GenericGenerator;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class ProductImage {
	@Id
	@GenericGenerator(name = "sequence_user_id", strategy = "com.ty.supermarketappspringboot.dto.ProductImageIdGenerator")
	@GeneratedValue(generator = "sequence_user_id")
	@ApiModelProperty(value = "AutoGenerated")
	private String id;

	private String name;

	private String type;

	@Lob
	@Column(length = 10000)
	private byte[] imageData;

}
