package com.ty.supermarketappspringboot.dto;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotBlank;

import org.hibernate.annotations.GenericGenerator;

import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
@Getter
@Setter
@Entity
public class Stock {
	@Id
	@GenericGenerator(name = "sequence_stock_id",strategy = "com.ty.supermarketappspringboot.dto.StockIdGenerator")
	@GeneratedValue(generator = "sequence_stock_id")
	@ApiModelProperty(value = "AutoGenerated")
	private String id;
	
	@NotBlank(message = "Please Enter The Stock-Type")
	@ApiModelProperty(required = true)
	private String type;
	
	@OneToMany(mappedBy = "stock",cascade = CascadeType.ALL)
	
	private List<Product> products;
	
	@ManyToOne
	@JoinColumn
	private SuperMarket superMarket;

}
